<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- 发布配置 (禁用 AOT/Trimming 以兼容 WinRT API) -->
    <PublishTrimmed>false</PublishTrimmed>
    <PublishAot>false</PublishAot>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>

    <!-- WinRT 配置 -->
    <CsWinRTIncludes>Windows.Devices.Bluetooth;Windows.Devices.Bluetooth.Audio</CsWinRTIncludes>

    <!-- 应用信息 -->
    <AssemblyName>Audiosink</AssemblyName>
    <RootNamespace>Audiosink</RootNamespace>
    <ApplicationIcon />
  </PropertyGroup>

  <!-- 依赖包 -->
  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.1.3" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
  </ItemGroup>

</Project>